### PR TITLE
Remove german phrases

### PR DESCRIPTION
**Pull request by wkbkhard**
I guess I now removed every german phrase

### CODE REVIEW

**Review by ksuess — CHANGES_REQUESTED** [review]
oh no! why do you remove the "krumme Angabe"?!

just run ./update.sh in locales and it's fine.

**Comment by wkbkhard** [comment]
Okay, I can't get it to run atm. And don't know why... Has to wait then

**Comment by ksuess** [comment]
I updated translation files. Would you mind translating your ids?
(Still sad to loose "krumme Angabe" ;-))

**Comment by wkbkhard** [comment]
I think all my translations I made are still there after updating or i misunderstood the assignment

**Pull request merged**
